CREATE SEQUENCE AUC_PRODUCT_AUTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUC_PROGRESS_AUTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUC_COMPLETE_AUTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUC_LOG_AUTO START WITH 1 INCREMENT BY 1;

