--------------------------------------------------------
--  颇老捞 积己凳 - 老夸老-5岿-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUC_ADMIN
--------------------------------------------------------

  CREATE TABLE "TEST"."AUC_ADMIN" 
   (	"ID" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AUC_COMPLETE
--------------------------------------------------------

  CREATE TABLE "TEST"."AUC_COMPLETE" 
   (	"ID" NUMBER, 
	"AUC_ID" NUMBER, 
	"COMPLETE_PRICE" NUMBER, 
	"TENDER_USER_ID" VARCHAR2(100 BYTE), 
	"UID_CHECK" DATE, 
	"TENDER_ID_CHECK" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AUC_INFORMATION
--------------------------------------------------------

  CREATE TABLE "TEST"."AUC_INFORMATION" 
   (	"PID" NUMBER, 
	"USER_ID" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"PNAME" VARCHAR2(100 BYTE), 
	"PSUBJECT" VARCHAR2(100 BYTE), 
	"PCONTENT" CLOB, 
	"PICTURE" VARCHAR2(500 BYTE), 
	"REGISTER_DATE" DATE, 
	"END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PCONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table AUC_INTEREST
--------------------------------------------------------

  CREATE TABLE "TEST"."AUC_INTEREST" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"INTEREST" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AUC_LOG
--------------------------------------------------------

  CREATE TABLE "TEST"."AUC_LOG" 
   (	"ID" NUMBER, 
	"PROGRESS_ID" NUMBER, 
	"TENDER_USER_ID" VARCHAR2(100 BYTE), 
	"TENDER_DATE" DATE, 
	"TENDER_PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AUC_NOTE
--------------------------------------------------------

  CREATE TABLE "TEST"."AUC_NOTE" 
   (	"SENDID" VARCHAR2(100 BYTE), 
	"RECEIVEID" VARCHAR2(100 BYTE), 
	"CONTENT" CLOB, 
	"CONDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table AUC_PROGRESS
--------------------------------------------------------

  CREATE TABLE "TEST"."AUC_PROGRESS" 
   (	"ID" NUMBER, 
	"PID" NUMBER, 
	"APP_DATE" DATE, 
	"ADMIN_APPROVAL" NUMBER(1,0), 
	"ADMIN_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AUC_USER
--------------------------------------------------------

  CREATE TABLE "TEST"."AUC_USER" 
   (	"ID" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(100 BYTE), 
	"ACCOUNT" VARCHAR2(100 BYTE), 
	"AUTHCODE" VARCHAR2(100 BYTE), 
	"STOPDATE" DATE, 
	"ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TEST.AUC_ADMIN
SET DEFINE OFF;
REM INSERTING into TEST.AUC_COMPLETE
SET DEFINE OFF;
REM INSERTING into TEST.AUC_INFORMATION
SET DEFINE OFF;
Insert into TEST.AUC_INFORMATION (PID,USER_ID,TITLE,PNAME,PSUBJECT,PICTURE,REGISTER_DATE,END_DATE) values (1,'1','13','13','1341','142342',to_date('19/05/22','RR/MM/DD'),to_date('19/06/11','RR/MM/DD'));
Insert into TEST.AUC_INFORMATION (PID,USER_ID,TITLE,PNAME,PSUBJECT,PICTURE,REGISTER_DATE,END_DATE) values (2,'1','id2','test','consodfsfe','twetewtew',to_date('19/05/22','RR/MM/DD'),to_date('19/05/22','RR/MM/DD'));
REM INSERTING into TEST.AUC_INTEREST
SET DEFINE OFF;
REM INSERTING into TEST.AUC_LOG
SET DEFINE OFF;
REM INSERTING into TEST.AUC_NOTE
SET DEFINE OFF;
REM INSERTING into TEST.AUC_PROGRESS
SET DEFINE OFF;
Insert into TEST.AUC_PROGRESS (ID,PID,APP_DATE,ADMIN_APPROVAL,ADMIN_ID) values (1,1,to_date('19/05/22','RR/MM/DD'),0,null);
Insert into TEST.AUC_PROGRESS (ID,PID,APP_DATE,ADMIN_APPROVAL,ADMIN_ID) values (2,2,to_date('19/05/22','RR/MM/DD'),0,null);
REM INSERTING into TEST.AUC_USER
SET DEFINE OFF;
Insert into TEST.AUC_USER (ID,PASSWORD,EMAIL,PHONE,ACCOUNT,AUTHCODE,STOPDATE,ADDRESS) values ('1','2','3@3','4','5','6',to_date('17/01/02','RR/MM/DD'),null);
Insert into TEST.AUC_USER (ID,PASSWORD,EMAIL,PHONE,ACCOUNT,AUTHCODE,STOPDATE,ADDRESS) values ('487em','hdghghffghfgh','$5q3nnw@haha','ds s s s s','nsnsnnsn','test',null,'snsnnssn');
Insert into TEST.AUC_USER (ID,PASSWORD,EMAIL,PHONE,ACCOUNT,AUTHCODE,STOPDATE,ADDRESS) values ('ggg','rjsdnr4809','gny3201@naver.com','010-9454-3289','123-123123-12312312','test',null,'酒聪具具具');
--------------------------------------------------------
--  DDL for Index SYS_C007597
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C007597" ON "TEST"."AUC_ADMIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007615
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C007615" ON "TEST"."AUC_COMPLETE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007605
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C007605" ON "TEST"."AUC_INFORMATION" ("PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007618
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C007618" ON "TEST"."AUC_INTEREST" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007612
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C007612" ON "TEST"."AUC_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."NOTE_PK" ON "TEST"."AUC_NOTE" ("SENDID", "RECEIVEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007609
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C007609" ON "TEST"."AUC_PROGRESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007596
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C007596" ON "TEST"."AUC_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AUC_ADMIN
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_ADMIN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUC_COMPLETE
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_COMPLETE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUC_INFORMATION
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_INFORMATION" ADD PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."AUC_INFORMATION" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."AUC_INFORMATION" MODIFY ("REGISTER_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."AUC_INFORMATION" MODIFY ("PNAME" NOT NULL ENABLE);
  ALTER TABLE "TEST"."AUC_INFORMATION" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUC_INTEREST
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_INTEREST" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUC_LOG
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_LOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUC_NOTE
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_NOTE" ADD CONSTRAINT "NOTE_PK" PRIMARY KEY ("SENDID", "RECEIVEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUC_PROGRESS
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_PROGRESS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."AUC_PROGRESS" ADD CHECK (admin_approval in (0,1)) ENABLE;
  ALTER TABLE "TEST"."AUC_PROGRESS" MODIFY ("ADMIN_APPROVAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUC_USER
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_USER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."AUC_USER" MODIFY ("AUTHCODE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."AUC_USER" MODIFY ("ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "TEST"."AUC_USER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."AUC_USER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TEST"."AUC_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AUC_COMPLETE
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_COMPLETE" ADD FOREIGN KEY ("AUC_ID")
	  REFERENCES "TEST"."AUC_INFORMATION" ("PID") ENABLE;
  ALTER TABLE "TEST"."AUC_COMPLETE" ADD FOREIGN KEY ("TENDER_USER_ID")
	  REFERENCES "TEST"."AUC_USER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUC_INFORMATION
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_INFORMATION" ADD CONSTRAINT "INFORMATION_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "TEST"."AUC_USER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUC_INTEREST
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_INTEREST" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "TEST"."AUC_USER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUC_LOG
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_LOG" ADD FOREIGN KEY ("PROGRESS_ID")
	  REFERENCES "TEST"."AUC_PROGRESS" ("ID") ENABLE;
  ALTER TABLE "TEST"."AUC_LOG" ADD FOREIGN KEY ("TENDER_USER_ID")
	  REFERENCES "TEST"."AUC_USER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUC_NOTE
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_NOTE" ADD FOREIGN KEY ("SENDID")
	  REFERENCES "TEST"."AUC_USER" ("ID") ENABLE;
  ALTER TABLE "TEST"."AUC_NOTE" ADD FOREIGN KEY ("RECEIVEID")
	  REFERENCES "TEST"."AUC_USER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUC_PROGRESS
--------------------------------------------------------

  ALTER TABLE "TEST"."AUC_PROGRESS" ADD FOREIGN KEY ("PID")
	  REFERENCES "TEST"."AUC_INFORMATION" ("PID") ENABLE;
  ALTER TABLE "TEST"."AUC_PROGRESS" ADD FOREIGN KEY ("ADMIN_ID")
	  REFERENCES "TEST"."AUC_ADMIN" ("ID") ENABLE;
